version: '3.8'

services:
  # PHP Service
  php:
    # image: sail-8.2/app
    build:
      context: ./docker/app
      dockerfile: ./Dockerfile-dev
    container_name: experiment_php
    volumes:
      - ./:/var/www/html
    ports:
        - '${APP_PORT:-80}:8000'
        - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
        WWWUSER: '${WWWUSER:-1001}'
        LARAVEL_SAIL: 1
        SAIL_XDEBUG_MODE: 'develop'
        XDEBUG_MODE: debug
        XDEBUG_CONFIG: client_host=host.docker.internal
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
        PHP_IDE_CONFIG: "serverName=localhost"
    networks:
      - experiment_net
  #Composer
  composer:
    image: composer/composer:2.6.5
    networks:
      - experiment_net
    ports:
      - "9002:9000"
    volumes:
      - "./:/composer"
    user: '${WWWUSER:-1001}'
    container_name: experiment_composer
    working_dir: /composer
    command: [ "install", "--ignore-platform-reqs" ]


networks:
  experiment_net:
    driver: bridge
